server:
  bind: "127.0.0.1"
  port: 8080

capture:
  max_body_mb: 20
  store: "memory"
  worker_pool_size: 10

routes:
  openai:
    mount: "/openai"
    upstream: "https://api.openai.com/v1"
  ollama:
    mount: "/ollama"
    upstream: "http://localhost:11434/v1"
  dmr:
    mount: "/dmr"
    upstream: "http://localhost:12434/engines/v1"
